baseURL = "https://mark.nerdskillz.tech/"
languageCode = "en"
title = "Mark Gooderum's Personal Resume Site"

[[module.imports]]
path = "github.com/hugo-toha/toha/v4"

[[module.mounts]]
source = "static/files"
target = "static/files"

[[module.mounts]]
source = "./node_modules/flag-icons/flags"
target = "static/flags"

[[module.mounts]]
source = "./node_modules/@fontsource/mulish/files"
target = "static/files"

[[module.mounts]]
source = "./node_modules/katex/dist/fonts"
target = "static/fonts"

[languages.en]
languageCode = "en"
languageName = "English"
title = "Mark Gooderum's Personal Resume Site"
weight = 1

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
background = "/images/site/background.jpg"
gitRepo = "https://github.com/hugo-toha/hugo-toha.github.io"
gitBranch = "main"

[params.logo]
main = "/images/site/main-logo.png"
inverted = "/images/site/inverted-logo.png"
favicon = "/images/site/favicon.png"

[params.topNavbar]
maxVisibleSections = 5

[params.features.theme]
enable = true

[params.features.theme.services]
light = true
dark = true
default = "system"

[params.features.portfolio]
enable = true

[params.features.blog]
enable = false
showAuthor = true

[params.features.blog.shareButtons]
facebook = true
twitter = true
linkedin = true
reddit = true
whatsapp = true
email = true

[params.features.notes]
enable = true

[params.features.comment]
enable = false

[params.features.comment.services.disqus]
shortName = "toha-example-site"

[params.features.analytics]
enabled = false

[params.features.analytics.services.google]
id = "G-H4LBG7NDFZ"

[params.features.support]
enable = false

[params.features.support.services.kofi]
user = "hossainemruz"
text = "Tip Me"
textColor = "#f9fafc"
backgroundColor = "#248aaa"

[params.features.toc]
enable = false

[params.features.tags]
enable = false
on_card = true

[params.features.flags]
enable = true

[params.features.embedpdf]
enable = true

[params.features.flowchart]
enable = true

[params.features.flowchart.services.mermaid]
theme = "forest"

[params.features.math]
enable = true

[[params.features.math.services.katex.delimiters]]
left = "$$"
right = "$$"
display = true

[[params.features.math.services.katex.delimiters]]
left = "\\\\["
right = "\\\\]"
display = true

[[params.features.math.services.katex.delimiters]]
left = "$"
right = "$"
display = false

[[params.features.math.services.katex.delimiters]]
left = "\\\\("
right = "\\\\)"
display = false

[params.features.syntaxHighlight]
enable = true

[params.features.syntaxHighlight.services.hljs]
noHighlightRe = "/^no-highlight$/i"

[params.features.videoPlayer]
enable = true

[params.features.videoPlayer.services]

[params.features.copyCodeButton]
enable = true

[params.features.readingTime]
enable = false

[params.features.pagination]
maxPostsPerPage = 12

[params.footer]
enable = true
template = "footer.html"

[params.footer.navigation]
enable = true
customMenus = true

[params.footer.contactMe]
enable = true

[params.footer.credentials]
enable = true

[params.footer.newsletter]
enable = false

[params.footer.disclaimer]
enable = true

